// lib/db/schema.ts
import {
    pgTable,
    text,
    integer,
    boolean,
    timestamp,
    uuid,
    jsonb,
    vector,
    index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const users = pgTable("users", {
    id: text("id").primaryKey(), // Clerk ID
    email: text("email"),
    subscriptionPlan: text("subscription_plan").default("basic").notNull(),
    coursesGenerated: integer("courses_generated").default(0).notNull(),
    currentStreak: integer("current_streak").default(0).notNull(),
    activityMap: jsonb("activity_map").default({}).notNull(),
    totalTimeSpent: integer("total_time_spent").default(0).notNull(),
    lastActive: timestamp("last_active"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

// 1. Replaces 'companions' - The main course entity
export const courses = pgTable("courses", {
    id: uuid("id").defaultRandom().primaryKey(),
    author: text("author").notNull(), // Clerk User ID
    topic: text("topic").notNull(), // The main subject they searched for
    duration: integer("duration").notNull(), // e.g., in weeks or hours
    difficulty: text("difficulty").notNull(), // beginner, intermediate, advanced
    cheatSheet: text("cheat_sheet"),
    timeSpent: integer("time_spent").default(0).notNull(), // in seconds
    isCompleted: boolean("isCompleted").default(false).notNull(),
    isPublic: boolean("is_public").default(false).notNull(),
    shareSlug: text("share_slug").unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

// 2. The Course Structure (Generated by Gemini)
export const chapters = pgTable("chapters", {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
        .references(() => courses.id, { onDelete: "cascade" })
        .notNull(),
    title: text("title").notNull(),
    content: text("content"),
    lessonText: text("lesson_text"),
    mermaidDiagram: text("mermaid_diagram"),
    order: integer("order").notNull(),
    isCompleted: boolean("isCompleted").default(false).notNull(),
    isBookmarked: boolean("isBookmarked").default(false).notNull(),
});

// 3. Quizzes associated with Chapters
export const quizzes = pgTable("quizzes", {
    id: uuid("id").defaultRandom().primaryKey(),
    chapterId: uuid("chapter_id")
        .references(() => chapters.id, { onDelete: "cascade" })
        .notNull(),
    score: integer("score"), // Null if not attempted yet
    isCompleted: boolean("isCompleted").default(false).notNull(),
});

// 4. Questions for the Quizzes
export const questions = pgTable("questions", {
    id: uuid("id").defaultRandom().primaryKey(),
    quizId: uuid("quiz_id")
        .references(() => quizzes.id, { onDelete: "cascade" })
        .notNull(),
    questionText: text("question_text").notNull(),
    options: jsonb("options").notNull(), // Array of strings: ["A", "B", "C", "D"]
    correctAnswer: integer("correct_answer").notNull(), // Index of the correct option
});

// 5. Flashcards for Chapters (with SM-2 Spaced Repetition)
export const flashcards = pgTable("flashcards", {
    id: uuid("id").defaultRandom().primaryKey(),
    chapterId: uuid("chapter_id")
        .references(() => chapters.id, { onDelete: "cascade" })
        .notNull(),
    front: text("front").notNull(),
    back: text("back").notNull(),
    // SM-2 Spaced Repetition fields
    easeFactor: integer("ease_factor").default(250).notNull(), // ×100 to avoid floats (2.5 = 250)
    interval: integer("interval").default(0).notNull(),         // days until next review
    nextReviewAt: timestamp("next_review_at").defaultNow().notNull(),
});

// 6. Documents uploaded for RAG
export const documents = pgTable("documents", {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
        .references(() => courses.id, { onDelete: "cascade" })
        .notNull(),
    filename: text("filename").notNull(),
    uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
});

// 7. Chunks and Embeddings for Documents
export const documentChunks = pgTable(
    "document_chunks",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        documentId: uuid("document_id")
            .references(() => documents.id, { onDelete: "cascade" })
            .notNull(),
        content: text("content").notNull(),
        embedding: vector("embedding", { dimensions: 768 }), // Gemini text-embedding-004 has 768 dims
    },
    (table) => [
        index("document_chunks_embedding_hnsw_idx").using(
            "hnsw",
            table.embedding.op("vector_cosine_ops")
        ),
    ]
);

// 8. Study Buddy Conversation History
export const studyBuddyMessages = pgTable("study_buddy_messages", {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
        .references(() => courses.id, { onDelete: "cascade" })
        .notNull(),
    userId: text("user_id").notNull(),
    role: text("role").notNull(), // "user" | "ai"
    content: text("content").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

// --- Relations ---
export const courseRelations = relations(courses, ({ many }) => ({
    chapters: many(chapters),
    documents: many(documents),
    studyBuddyMessages: many(studyBuddyMessages),
}));

export const chapterRelations = relations(chapters, ({ one, many }) => ({
    course: one(courses, {
        fields: [chapters.courseId],
        references: [courses.id],
    }),
    quizzes: many(quizzes),
    flashcards: many(flashcards),
}));

export const quizRelations = relations(quizzes, ({ one, many }) => ({
    chapter: one(chapters, {
        fields: [quizzes.chapterId],
        references: [chapters.id],
    }),
    questions: many(questions),
}));

export const questionRelations = relations(questions, ({ one }) => ({
    quiz: one(quizzes, {
        fields: [questions.quizId],
        references: [quizzes.id],
    }),
}));

export const flashcardRelations = relations(flashcards, ({ one }) => ({
    chapter: one(chapters, {
        fields: [flashcards.chapterId],
        references: [chapters.id],
    }),
}));

export const documentRelations = relations(documents, ({ one, many }) => ({
    course: one(courses, {
        fields: [documents.courseId],
        references: [courses.id],
    }),
    chunks: many(documentChunks),
}));

export const documentChunkRelations = relations(documentChunks, ({ one }) => ({
    document: one(documents, {
        fields: [documentChunks.documentId],
        references: [documents.id],
    }),
}));

export const studyBuddyMessageRelations = relations(studyBuddyMessages, ({ one }) => ({
    course: one(courses, {
        fields: [studyBuddyMessages.courseId],
        references: [courses.id],
    }),
}));

// 9. Analytics Telemetry Events
export const events = pgTable("events", {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id").notNull(),
    eventType: text("event_type").notNull(), // "course_generated" | "quiz_completed" | "flashcard_reviewed" | "pdf_uploaded"
    metadata: jsonb("metadata").default({}).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});
