// lib/db/schema.ts
import {
    pgTable,
    text,
    integer,
    boolean,
    timestamp,
    uuid,
    jsonb,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const users = pgTable("users", {
    id: text("id").primaryKey(), // Clerk ID
    email: text("email"),
    coursesGenerated: integer("courses_generated").default(0).notNull(),
    currentStreak: integer("current_streak").default(0).notNull(),
    activityMap: jsonb("activity_map").default({}).notNull(),
    totalTimeSpent: integer("total_time_spent").default(0).notNull(),
    lastActive: timestamp("last_active"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

// 1. Replaces 'companions' - The main course entity
export const courses = pgTable("courses", {
    id: uuid("id").defaultRandom().primaryKey(),
    author: text("author").notNull(), // Clerk User ID
    topic: text("topic").notNull(), // The main subject they searched for
    duration: integer("duration").notNull(), // e.g., in weeks or hours
    difficulty: text("difficulty").notNull(), // beginner, intermediate, advanced
    timeSpent: integer("time_spent").default(0).notNull(), // in seconds
    isCompleted: boolean("isCompleted").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

// 2. The Course Structure (Generated by Gemini)
export const chapters = pgTable("chapters", {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
        .references(() => courses.id, { onDelete: "cascade" })
        .notNull(),
    title: text("title").notNull(),
    content: text("content"),
    lessonText: text("lesson_text"),
    order: integer("order").notNull(),
    isCompleted: boolean("isCompleted").default(false).notNull(),
    isBookmarked: boolean("isBookmarked").default(false).notNull(),
});

// 3. Quizzes associated with Chapters
export const quizzes = pgTable("quizzes", {
    id: uuid("id").defaultRandom().primaryKey(),
    chapterId: uuid("chapter_id")
        .references(() => chapters.id, { onDelete: "cascade" })
        .notNull(),
    score: integer("score"), // Null if not attempted yet
    isCompleted: boolean("isCompleted").default(false).notNull(),
});

// 4. Questions for the Quizzes
export const questions = pgTable("questions", {
    id: uuid("id").defaultRandom().primaryKey(),
    quizId: uuid("quiz_id")
        .references(() => quizzes.id, { onDelete: "cascade" })
        .notNull(),
    questionText: text("question_text").notNull(),
    options: jsonb("options").notNull(), // Array of strings: ["A", "B", "C", "D"]
    correctAnswer: integer("correct_answer").notNull(), // Index of the correct option
});

// --- Relations ---
export const courseRelations = relations(courses, ({ many }) => ({
    chapters: many(chapters),
}));

export const chapterRelations = relations(chapters, ({ one, many }) => ({
    course: one(courses, {
        fields: [chapters.courseId],
        references: [courses.id],
    }),
    quizzes: many(quizzes),
}));

export const quizRelations = relations(quizzes, ({ one, many }) => ({
    chapter: one(chapters, {
        fields: [quizzes.chapterId],
        references: [chapters.id],
    }),
    questions: many(questions),
}));

export const questionRelations = relations(questions, ({ one }) => ({
    quiz: one(quizzes, {
        fields: [questions.quizId],
        references: [quizzes.id],
    }),
}));
